=== api-evangelist/google-tag-manager/json-schema/google-tag-manager-v2-container-features-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "ContainerFeatures",
  "type": "object",
  "description": "Read-only container feature set.",
  "properties": {
    "supportUserPermissions": {
      "type": "boolean"
    },
    "supportEnvironments": {
      "type": "boolean"
    },
    "supportWorkspaces": {
      "type": "boolean"
    },
    "supportGtagConfigs": {
      "type": "boolean"
    },
    "supportBuiltInVariables": {
      "type": "boolean"
    },
    "supportClients": {
      "type": "boolean"
    },
    "supportFolders": {
      "type": "boolean"
    },
    "supportTags": {
      "type": "boolean"
    },
    "supportTemplates": {
      "type": "boolean"
    },
    "supportTriggers": {
      "type": "boolean"
    },
    "supportVariables": {
      "type": "boolean"
    },
    "supportVersions": {
      "type": "boolean"
    },
    "supportZones": {
      "type": "boolean"
    },
    "supportTransformations": {
      "type": "boolean"
    }
  }
}

=== api-evangelist/google-tag-manager/examples/google-tag-manager-v2-container-features-example.json
{
  "supportUserPermissions": true,
  "supportEnvironments": true,
  "supportWorkspaces": true,
  "supportGtagConfigs": true,
  "supportBuiltInVariables": true,
  "supportClients": true,
  "supportFolders": true,
  "supportTags": true,
  "supportTemplates": true,
  "supportTriggers": true,
  "supportVariables": true,
  "supportVersions": true,
  "supportZones": true,
  "supportTransformations": true
}
